version: "3.8"

services:
  unifi-db:
    image: mongo:4.4.18
    container_name: unifi-db
    restart: unless-stopped
    networks:
      - unifi-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=change_me_root_pass
    volumes:
      - /volume4/app_configs/unifi/mongo:/data/db
      - /volume4/app_configs/unifi/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi
    restart: unless-stopped
    depends_on:
      - unifi-db
    networks:
      - unifi-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles

      # Mongo connection (required for this image)
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MONGO_USER=unifi
      - MONGO_PASS=change_me_unifi_pass

    volumes:
      - /volume4/app_configs/unifi/config:/config

    ports:
      - "10001:10001/udp"   # AP discovery
      - "3478:3478/udp"     # STUN
      - "18443:8443"        # UniFi web UI: https://NAS:18443
      - "18080:8080"        # Device inform: http://NAS:18080/inform
      - "18880:8880"        # Guest portal HTTP (optional)
      - "18843:8843"        # Guest portal HTTPS (optional)
      - "16789:6789"        # Speed test (optional)
      # - "1900:1900/udp"   # optional multicast discovery

networks:
  unifi-net:
    driver: bridge
