version: "3.8"

services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /volume4/app_configs/unifi/config:/config

    ports:
      - "10001:10001/udp"   # AP discovery
      - "3478:3478/udp"     # STUN
      - "18443:8443"        # UniFi web UI
      - "18080:8080"        # Device inform
      - "18880:8880"        # Guest portal HTTP
      - "18843:8843"        # Guest portal HTTPS 
      - "16789:6789"        # Speed test (optional)

      # Optional: multicast discovery (often not needed)
      # - "1900:1900/udp"
